---
- file: dest=/opt/greetings state=directory mode=0755
- shell: aws s3 cp s3://{{ deploy_bucket }}/deploy/{{ app_binary }} /opt/greetings/{{ app_binary }} 
- template: src=greetings.j2 dest=/etc/init.d/greetings mode=0755
- shell: update-rc.d greetings defaults 
