---
- template: src=upstart.j2 dest=/etc/init/greetings.conf mode=0644
  when:
  - ansible_distribution_version < '16.04'
  - ansible_distribution == "Ubuntu"

- template: src=systemd.j2 dest=/lib/systemd/system/greetings.service mode=0644
  when:
  - ansible_distribution_version >= '16.04'
  - ansible_distribution == "Ubuntu"
