---
- hosts: "*vagrant:localhost"
  sudo: True
  roles:
  - smola.java
  - greetings
  vars:
    java_packages: oracle-java8-installer
    deploy_bucket: iotcloud-d-vr-sysctl
    app_binary: gs-spring-boot-0.1.0.jar
